name: teacher
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  model:
    path: ../../model  

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  flutter_launcher_icons: ^0.14.3
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  lottie: ^3.3.1
  intl_phone_field: ^3.2.0
  cloud_firestore: ^5.6.6
  provider: ^6.1.5
  uuid: ^4.5.1
  table_calendar: ^3.2.0
  intl: ^0.20.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Animation/welcome.json
    - assets/Animation/otp.json

