// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9uop8dr1NA_EjjrXRhfSvjbS3pXen7lI',
    appId: '1:13968475849:web:86d0ffc32a5258599f2f18',
    messagingSenderId: '13968475849',
    projectId: 'ssmm-514fe',
    authDomain: 'ssmm-514fe.firebaseapp.com',
    storageBucket: 'ssmm-514fe.firebasestorage.app',
    measurementId: 'G-CMMX5FBRJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf-01FHkqM5zDGgcaO4aLNm-4U8jbYpbc',
    appId: '1:13968475849:android:964d13af9a4657959f2f18',
    messagingSenderId: '13968475849',
    projectId: 'ssmm-514fe',
    storageBucket: 'ssmm-514fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqvTAX2vyDTZwXPrTe_GA_-7FPi0Y2Bdw',
    appId: '1:13968475849:ios:41d3add3758813399f2f18',
    messagingSenderId: '13968475849',
    projectId: 'ssmm-514fe',
    storageBucket: 'ssmm-514fe.firebasestorage.app',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqvTAX2vyDTZwXPrTe_GA_-7FPi0Y2Bdw',
    appId: '1:13968475849:ios:41d3add3758813399f2f18',
    messagingSenderId: '13968475849',
    projectId: 'ssmm-514fe',
    storageBucket: 'ssmm-514fe.firebasestorage.app',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9uop8dr1NA_EjjrXRhfSvjbS3pXen7lI',
    appId: '1:13968475849:web:9ff97c5863e1b6ae9f2f18',
    messagingSenderId: '13968475849',
    projectId: 'ssmm-514fe',
    authDomain: 'ssmm-514fe.firebaseapp.com',
    storageBucket: 'ssmm-514fe.firebasestorage.app',
    measurementId: 'G-293EJEF5EZ',
  );
}
